# Generated by Django 5.0.3 on 2024-04-08 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_app', '0003_product_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date',
            new_name='date_field',
        ),
    ]
