# Generated by Django 5.0.3 on 2024-04-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_app', '0004_rename_date_product_date_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_field',
            field=models.DateField(),
        ),
    ]
