# Generated by Django 5.0.3 on 2024-04-08 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_app', '0006_product_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rating',
            new_name='rating_field',
        ),
    ]
