# Generated by Django 5.0.3 on 2025-01-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paymentIntrigation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="number",
            field=models.IntegerField(default=0),
        ),
    ]
