# Generated by Django 5.0.3 on 2025-01-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paymentIntrigation", "0002_orders_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrdersUpdate",
            fields=[
                ("update_id", models.AutoField(primary_key=True, serialize=False)),
                ("order_id", models.IntegerField(default="")),
                ("update_desc", models.CharField(max_length=5000)),
                ("timestamp", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
