# Generated by Django 5.0.3 on 2025-01-30 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paymentIntrigation", "0003_ordersupdate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordersupdate",
            name="order_id",
        ),
        migrations.AddField(
            model_name="ordersupdate",
            name="order",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updates",
                to="paymentIntrigation.orders",
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="address",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="orders",
            name="zip_code",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="ordersupdate",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="ordersupdate",
            name="update_desc",
            field=models.TextField(),
        ),
    ]
